export const TOUR_STEPS = [
  {
    id: 'draft-mode',
    target: 'draft-badge',
    title: 'Draft mode',
    description: "You're working in a draft. Changes are saved automatically, and won't go live until you publish.",
    dialogSide: 'bottom',
    spotlightPadding: 8,
    borderRadius: 999,
  },
  {
    id: 'completeness-score',
    target: 'completeness-button',
    title: 'Completeness score',
    description: 'Check the completeness status of your product in the Default values tab. Open the modal to see which attributes are still missing and easily navigate directly to them for editing.',
    dialogSide: 'bottom',
    spotlightPadding: 8,
    borderRadius: 999,
  },
  {
    id: 'tab-structure',
    target: 'tab-structure',
    title: 'Default & Channel values',
    description: 'Set the default values that apply to all channels. Then use channel values when a specific channel needs different information.',
    dialogSide: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'variant-selector',
    target: 'variant-selector',
    title: 'Select variant + language',
    description: 'Choose the variant and language you want to edit. Some values are shared across variants or languages, while others apply only to the selected combination.',
    dialogSide: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'attribute-badges',
    target: 'attribute-badge',
    title: 'How attributes work',
    description: 'Badges on each field show whether it can vary by variant (V), channel (C), or language (L).',
    dialogSide: 'left',
    spotlightPadding: 8,
    borderRadius: 100,
  },
  {
    id: 'publish-button',
    target: 'publish-button',
    title: 'Adding product to the catalog',
    description: 'Adding the product to the catalog saves it within your product database. This does not make it live on the website — that\'s a separate action you\'ll perform manually later when you\'re ready to publish it to your customers.',
    dialogSide: 'bottom',
    spotlightPadding: 8,
  },
]
